name: WAFA Scraper

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 08:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Or your preferred version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run WAFA scraper
        run: python your_script_name.py  # <-- Replace with your script filename

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Automated update: latest WAFA news" || echo "No changes to commit"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
